name: lab_15
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  image_picker: ^0.8.9
  permission_handler: ^10.3.0
  app_settings: ^4.2.0
  cloud_firestore: ^4.8.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
